### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by andercard0** [Hipnosis183/Viridian#1]
Hi,

Just seen the project and decided to test since there is no releases available, but at the end of the building process I run the program see how it opens.. am i missing something here ?

![image](https://github.com/Hipnosis183/Viridian/assets/43047877/6399cbf1-8d5e-4e45-b559-125bad3bc1b2)

**Comment by Hipnosis183** [comment]
Hey Anderson

I've been doing some changes recently, and also updated some dependencies. Make sure you have the most recent installed by running `npm install` again.

If the problem persists, try running the development version and report back any error messages in the dev console. First run the Angular server with `npm run start:angular`, and then the Electron server with `npm run start:electron`.

**Comment by andercard0** [comment]
> Hey Anderson
> 
> I've been doing some changes recently, and also updated some dependencies. Make sure you have the most recent installed by running `npm install` again.
> 
> If the problem persists, try running the development version and report back any error messages in the dev console. First run the Angular server with `npm run start:angular`, and then the Electron server with `npm run start:electron`.

Thanks for the heads up, I've redownloaded the whole project again but
When i run npm install (Results are as follows)

![image](https://github.com/Hipnosis183/Viridian/assets/43047877/3be30fa4-f906-4b76-82bc-169dcd86da38)

Development version ?
I could not identify any other branch 🤔 

Did run the commands you mentioned and:
(looks stuck nothing happens at all)
![image](https://github.com/Hipnosis183/Viridian/assets/43047877/de3197d8-b239-4952-a5ba-f36e82645e24)

Also, any other command i run after this does nothing at all

![image](https://github.com/Hipnosis183/Viridian/assets/43047877/14e7f9f1-c7e3-4866-a04c-5269e91f4582)

But if i ctrl + c to stop it and try for example run
npm run package

![image](https://github.com/Hipnosis183/Viridian/assets/43047877/5ee78630-4a06-4d15-af9e-44ebdd6b9969)

npm run package:win32 command does work/build but
Terminal output returns:
![image](https://github.com/Hipnosis183/Viridian/assets/43047877/b45487e1-d39c-490c-813c-551a85e6867f)

And when try to run the program it is worse now lol
![image](https://github.com/Hipnosis183/Viridian/assets/43047877/3017ef7e-f77e-462a-ba1a-fa63b322503b)

I'm sorry if I'm being noob here but electron stuff aren't my thing yet : /

**Comment by Hipnosis183** [comment]
It's okay, don't worry

The `npm install` is fine, it's just some warnings from deprecated dependencies of dependencies.

The development server is just running a different script that enables the dev console and live updates, everything is already included on the main branch. You just have to run the commands in parallel. First start the Angular server, and once it finished building run the Electron server in a different terminal instance.

Remember to close the Angular with ctrl+c whenever you close the Electron window, since the server doesn't stop by itself.

**Comment by andercard0** [comment]
> It's okay, don't worry
> 
> The `npm install` is fine, it's just some warnings from deprecated dependencies of dependencies.
> 
> The development server is just running a different script that enables the dev console and live updates, everything is already included on the main branch. You just have to run the commands in parallel. First start the Angular server, and once it finished building run the Electron server in a different terminal instance.
> 
> Remember to close the Angular with ctrl+c whenever you close the Electron window, since the server doesn't stop by itself.

Ahh. great! 
Now we're talking thank you!
Will try to build it for use now instead in debug mode.
![image](https://github.com/Hipnosis183/Viridian/assets/43047877/61dc48d6-f8c9-4951-9c12-da990911259a)
